openapi: 3.1.1
info:
  title: CMI5 Container API
  description: API for managing CMI5 learning content containers
  version: 1.0.0
  license:
    name: "Apache-2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0

security:
  - bearerAuth: []

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /dummmy:
    get:
      summary: Dummy path to include cmi5 defs
      operationId: getDummy
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              example: |
                <cmi5 xmlns="https://w3id.org/xapi/profiles/cmi5/v1/CourseStructure.xsd">
                  <course>
                    <components>
                      <component>
                        <id>12345</id>
                        <title>Sample Course</title>
                      </component>
                    </components>
                  </course>
                </cmi5>
              schema:
                xml:
                  name: cmi5
                type: object
                $ref: "cmi5.yaml#/components/schemas/CMI5"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Container:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - name
